name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Validate content
        run: npx ptcomply validate

      - name: Verify site build
        run: npx ptcomply build
